# Generated by Django 4.0.3 on 2022-04-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_myfile_delete_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfile',
            old_name='description',
            new_name='projectName',
        ),
    ]
